// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commentservice/api/comment.proto

package comment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Comment              string   `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_931e41d815147d4e, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Comment              string               `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_931e41d815147d4e, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "comment.CreateRequest")
	proto.RegisterType((*Response)(nil), "comment.Response")
}

func init() {
	proto.RegisterFile("commentservice/api/comment.proto", fileDescriptor_931e41d815147d4e)
}

var fileDescriptor_931e41d815147d4e = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbd, 0x4e, 0xc3, 0x40,
	0x10, 0x84, 0xb1, 0x89, 0x02, 0x59, 0x44, 0x24, 0xb6, 0x40, 0x96, 0x9b, 0x18, 0x57, 0xa9, 0xce,
	0x52, 0x10, 0x05, 0x05, 0x05, 0xa4, 0xa0, 0x37, 0x54, 0x34, 0xe8, 0x62, 0x2f, 0xd1, 0x49, 0xb9,
	0x3b, 0xe3, 0xdb, 0xf0, 0x02, 0xbc, 0x38, 0xd2, 0xfd, 0xf0, 0xa7, 0x74, 0xbb, 0xa3, 0xdd, 0xd1,
	0x37, 0x03, 0x55, 0x67, 0xb5, 0x26, 0xc3, 0x8e, 0xc6, 0x0f, 0xd5, 0x51, 0x23, 0x07, 0xd5, 0x44,
	0x49, 0x0c, 0xa3, 0x65, 0x8b, 0x27, 0x71, 0x2d, 0x17, 0x5b, 0x6b, 0xb7, 0x3b, 0x6a, 0xbc, 0xbc,
	0xd9, 0xbf, 0x35, 0xac, 0x34, 0x39, 0x96, 0x7a, 0x08, 0x97, 0xf5, 0x1d, 0x9c, 0xaf, 0x47, 0x92,
	0x4c, 0x2d, 0xbd, 0xef, 0xc9, 0x31, 0x16, 0x90, 0x9e, 0x8b, 0xac, 0xca, 0x96, 0xb3, 0x36, 0xad,
	0x88, 0x30, 0x31, 0x52, 0x53, 0x91, 0x7b, 0xd9, 0xcf, 0xf5, 0x67, 0x06, 0xa7, 0x2d, 0xb9, 0xc1,
	0x1a, 0x47, 0x38, 0x87, 0x5c, 0xf5, 0xf1, 0x2b, 0x57, 0xfd, 0x6f, 0xab, 0xfc, 0xb0, 0xd5, 0xf1,
	0x8f, 0x15, 0xde, 0x02, 0x74, 0x9e, 0xa4, 0x7f, 0x95, 0x5c, 0x4c, 0xaa, 0x6c, 0x79, 0xb6, 0x2a,
	0x45, 0xe0, 0x17, 0x89, 0x5f, 0x3c, 0x27, 0xfe, 0x76, 0x16, 0xaf, 0xef, 0x79, 0xf5, 0x08, 0xf3,
	0x75, 0x70, 0x7e, 0x0a, 0x95, 0xe0, 0x0d, 0x4c, 0x43, 0x2c, 0xbc, 0x14, 0xa9, 0x9a, 0x3f, 0x39,
	0xcb, 0x8b, 0x6f, 0x3d, 0xf1, 0xd7, 0x47, 0x0f, 0x57, 0x2f, 0x8b, 0x7f, 0xdd, 0x2a, 0xc3, 0x34,
	0x1a, 0xb9, 0x4b, 0x05, 0x6f, 0xa6, 0x1e, 0xe5, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x20, 0x35,
	0x9e, 0xcf, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommentServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/comment.CommentService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
type CommentServiceServer interface {
	Create(context.Context, *CreateRequest) (*Response, error)
}

// UnimplementedCommentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommentServiceServer struct {
}

func (*UnimplementedCommentServiceServer) Create(ctx context.Context, req *CreateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterCommentServiceServer(s *grpc.Server, srv CommentServiceServer) {
	s.RegisterService(&_CommentService_serviceDesc, srv)
}

func _CommentService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comment.CommentService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "comment.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CommentService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commentservice/api/comment.proto",
}
